### ISSUE TITLE
100% cpu usage whilst lein kinesis is running

### ISSUE THREAD

**Issue by joelittlejohn** [mdaley/lein-kinesis#3]
This block causes the plugin to use 100% of my CPU whilst the plugin is running:

``` clj
(defn- run-kinesis
  "Run the kinesis server"
  [port]
  (let [p (proc "kinesalite" "--port" (str port) :verbose :very)]
    (while true
      (try
        (stream-to-out p :out)
        (catch Exception e (println (str e)))))))
```

**Comment by mdaley** [comment]
That is strange.  Don't get it myself.  Have you plugged the plugin into a project for testing purposes or are you just running it by itself?  I think what is happening here is that `stream-to-out` blocks and just streams from the process to stdout.  The reason for the while loop is to catch any error and then start streaming to stdout again.  Perhaps it could be simplified to just the `stream-to-out` statement without the loop, or a `future` wrapping it with a loop with waits after it?  I'll try these when I get a chance.

**Comment by mdaley** [comment]
I've updated the plugin in a few ways, hopefully solving this problem. Can you tell me whether the issue still exists when you try it in your own project?

**Comment by joelittlejohn** [comment]
Hey @mdaley thanks for jumping on this. Apologies for going a bit quiet, I didn't get a chance to look into this after raising the issue. I'll give you a shout if I notice any more strange behaviour. Cheers!
